// Table columns configuration
export function useTableColumns(t) {
  return {
    countryColumns: [
      { key: "id", header: t("id"), type: "text" },
      { key: "name", header: t("name"), type: "text" },
      { key: "created_at", header: t("createdAt"), type: "date" },
      { key: "updated_at", header: t("updatedAt"), type: "date" },
    ],

    cityColumns: [
      { key: "id", header: t("id"), type: "text" },
      { key: "name", header: t("name"), type: "text" },
      { key: "created_at", header: t("createdAt"), type: "date" },
      { key: "updated_at", header: t("updatedAt"), type: "date" },
    ],

    zoneColumns: [
      { key: "id", header: t("id"), type: "text" },
      { key: "name", header: t("name"), type: "text" },
      { key: "created_at", header: t("createdAt"), type: "date" },
      { key: "updated_at", header: t("updatedAt"), type: "date" },
    ],

    districtColumns: [
      { key: "id", header: t("id"), type: "text" },
      { key: "name", header: t("name"), type: "text" },
      { key: "created_at", header: t("createdAt"), type: "date" },
      { key: "updated_at", header: t("updatedAt"), type: "date" },
    ],

    projectColumns: [
      { header: t("id"), key: "id" },
      { header: t("name"), key: "name" },
      { header: t("startDate"), key: "start_date", type: "date" },
      { header: t("endDate"), key: "end_date", type: "date" },
      { header: t("expectedDate"), key: "expected_date", type: "date" },
      { header: t("customerId"), key: "customer_id", type: "text" },
      { header: t("createdAt"), key: "created_at", type: "date" },
      { header: t("updatedAt"), key: "updated_at", type: "date" },
    ],

    costCenterColumns: [
      { header: t("id"), key: "id" },
      { header: t("code"), key: "code" },
      { header: t("name"), key: "name" },
      { header: t("subOf"), key: "sub_cost_center_of", type: "text" },
      { header: t("active"), key: "active", type: "boolean" },
      { header: t("createdAt"), key: "created_at", type: "date" },
      { header: t("updatedAt"), key: "updated_at", type: "date" },
    ],

    departmentColumns: [
      { header: t("id"), key: "id" },
      { header: t("code"), key: "code" },
      { header: t("name"), key: "name" },
      { header: t("subOf"), key: "sub_department_of", type: "text" },
      { header: t("active"), key: "active", type: "boolean" },
      { header: t("createdAt"), key: "created_at", type: "date" },
      { header: t("updatedAt"), key: "updated_at", type: "date" },
    ],

    tradesColumns: [
      { header: t("id"), key: "id" },
      { header: t("code"), key: "code" },
      { header: t("name"), key: "name" },
      { header: t("active"), key: "active", type: "boolean" },
      { header: t("createdAt"), key: "created_at", type: "date" },
      { header: t("updatedAt"), key: "updated_at", type: "date" },
    ],

    companyCodesColumns: [
      { header: t("id"), key: "id" },
      { header: t("code"), key: "code" },
      { header: t("name"), key: "name" },
      { header: t("createdAt"), key: "created_at", type: "date" },
      { header: t("updatedAt"), key: "updated_at", type: "date" },
    ],

    jobsColumns: [
      { header: t("id"), key: "id" },
      { header: t("code"), key: "code" },
      { header: t("description"), key: "description" },
      { header: t("projectId"), key: "project_id" },
      { header: t("startDate"), key: "start_date", type: "date" },
      { header: t("expectedDate"), key: "expected_date", type: "date" },
      { header: t("endDate"), key: "end_date", type: "date" },
      { header: t("createdAt"), key: "created_at", type: "date" },
      { header: t("updatedAt"), key: "updated_at", type: "date" },
    ],

    productLinesColumns: [
      { header: t("id"), key: "id" },
      { header: t("code"), key: "code" },
      { header: t("name"), key: "name" },
      { header: t("active"), key: "active", type: "boolean" },
      { header: t("createdAt"), key: "created_at", type: "date" },
      { header: t("updatedAt"), key: "updated_at", type: "date" },
    ],  

    categoriesColumns: [
      { header: t("id"), key: "id" },
      { header: t("code"), key: "code" },
      { header: t("name"), key: "name" },
      { header: t("subOf"), key: "subcategory_of" },
      { header: t("active"), key: "active", type: "boolean" },
      { header: t("createdAt"), key: "created_at", type: "date" },
      { header: t("updatedAt"), key: "updated_at", type: "date" },
    ],

    brandsColumns: [
      { header: t("id"), key: "id" },
      { header: t("code"), key: "code" },
      { header: t("name"), key: "name" },
      { header: t("subOf"), key: "subbrand_of" },
      { header: t("active"), key: "active", type: "boolean" },
      { header: t("createdAt"), key: "created_at", type: "date" },
      { header: t("updatedAt"), key: "updated_at", type: "date" },
    ],

    itemsColumns: [
      { header: t("id"), key: "id" },
      { header: t("code"), key: "code" },
      { header: t("name"), key: "name" },
      { header: t("productLine"), key: "product_line_name" },
      { header: t("category"), key: "category_name" },
      { header: t("brand"), key: "brand_name" },
      { header: t("active"), key: "active", type: "boolean" },
      { header: t("createdAt"), key: "created_at", type: "date" },
      { header: t("updatedAt"), key: "updated_at", type: "date" },
    ],

    customerGroupColumns: [
      { header: t("id"), key: "id" },
      { header: t("code"), key: "code" },
      { header: t("name"), key: "name" },
      { header: t("active"), key: "active", type: "boolean" },
      { header: t("createdAt"), key: "created_at", type: "date" },
      { header: t("updatedAt"), key: "updated_at", type: "date" },
    ],

    salesmenColumns: [
      { header: t("id"), key: "id" },
      { header: t("code"), key: "code" },
      { header: t("name"), key: "name" },
      { header: t("address"), key: "address" },
      { header: t("phone1"), key: "phone1" },
      { header: t("phone2"), key: "phone2" },
      { header: t("email"), key: "email" },
      { header: t("isManager"), key: "is_manager", type: "boolean"  },
      { header: t("isSupervisor"), key: "is_supervisor", type: "boolean"  },
      { header: t("isCollector"), key: "is_collector", type: "boolean"  },
      { header: t("fixCommission"), key: "fix_commission" },
      { header: t("commissionByItem"), key: "commission_by_item" },
      { header: t("active"), key: "active", type: "boolean" },
      { header: t("createdAt"), key: "created_at", type: "date" },
      { header: t("updatedAt"), key: "updated_at", type: "date" },
    ],
     customerColumns: [
      { header: t("id"), key: "id" },
      { header: t("title"), key: "title" },
      { header: t("firstName"), key: "first_name" },
      { header: t("middleName"), key: "middle_name" },
      { header: t("lastName"), key: "last_name" },
      { header: t("displayName"), key: "display_name" },
      { header: t("companyName"), key: "company_name" },
      { header: t("phone1"), key: "phone1" },
      { header: t("phone2"), key: "phone2" },
      { header: t("phone3"), key: "phone3" },
      { header: t("fileNumber"), key: "file_number" },
      { header: t("barCode"), key: "bar_code" },
      { header: t("searchTerms"), key: "search_terms" },
      { header: t("indicator"), key: "indicator" },
      { header: t("riskCategory"), key: "risk_category" },
      { header: t("active"), key: "active", type: "boolean" },
      { header: t("blackListed"), key: "black_listed", type: "boolean" },
      { header: t("oneTimeAccount"), key: "one_time_account", type: "boolean" },
      { header: t("specialAccount"), key: "special_account", type: "boolean" },
      { header: t("posCustomer"), key: "pos_customer", type: "boolean" },
      { header: t("freeDeliveryCharge"), key: "free_delivery_charge", type: "boolean" },
      { header: t("printInvoiceLanguage"), key: "print_invoice_language" },
      { header: t("sendInvoice"), key: "send_invoice" },
      { header: t("addMessage"), key: "add_message", type: "boolean" },
      { header: t("invoiceMessage"), key: "invoice_message" },
      { header: t("notes"), key: "notes" },
      { header: t("customerGroup"), key: "customer_group_name" },
      { header: t("salesman"), key: "salesman_name" },
      { header: t("collector"), key: "collector_name" },
      { header: t("supervisor"), key: "supervisor_name" },
      { header: t("manager"), key: "manager_name" },
      { header: t("paymentTerm"), key: "payment_term_name" },
      { header: t("paymentMethod"), key: "payment_method_name" },
      { header: t("addressesCount"), key: "addresses_count" },
      { header: t("contactsCount"), key: "contacts_count" },
      { header: t("attachmentsCount"), key: "attachments_count" },
      { header: t("createdAt"), key: "created_at", type: "date" },
      { header: t("updatedAt"), key: "updated_at", type: "date" },
    ],
    paymentTermsColumns: [
      { key: "id", header: t("id"), type: "text" },
      { key: "code", header: t("code"), type: "text" },
      { key: "name", header: t("name"), type: "text" },
      { key: "nb_days", header: t("nbOfDays"), type: "number", render: (value) => (value == null || value === "" ? 0 : value) },
      { key: "active", header: t("active"), type: "boolean" },
      { key: "created_at", header: t("createdAt"), type: "date" },
      { key: "updated_at", header: t("updatedAt"), type: "date" },
    ],
    paymentMethodsColumns: [
      { key: "id", header: t("id"), type: "text" },
      { key: "code", header: t("code"), type: "text" },
      { key: "name", header: t("name"), type: "text" },
      { key: "is_credit_card", header: t("isCreditCard"), type: "boolean" },
      { key: "is_online_payment", header: t("isOnlinePayment"), type: "boolean" },
      { key: "active", header: t("active"), type: "boolean" },
      { key: "created_at", header: t("createdAt"), type: "date" },
      { key: "updated_at", header: t("updatedAt"), type: "date" },
    ],

    businessTypesColumns: [
      { header: t("id"), key: "id" },
      { header: t("code"), key: "code" },
      { header: t("name"), key: "name" },
      { header: t("createdAt"), key: "created_at", type: "date" },
      { header: t("updatedAt"), key: "updated_at", type: "date" },
    ],

    salesChannelsColumns: [
      { header: t("id"), key: "id" },
      { header: t("code"), key: "code" },
      { header: t("name"), key: "name" },
      { header: t("subOf"), key: "sub_sales_of" },
      { header: t("createdAt"), key: "created_at", type: "date" },
      { header: t("updatedAt"), key: "updated_at", type: "date" },
    ],

    distributionChannelsColumns: [
      { header: t("id"), key: "id" },
      { header: t("code"), key: "code" },
      { header: t("name"), key: "name" },
      { header: t("subOf"), key: "sub_distribution_of" },
      { header: t("createdAt"), key: "created_at", type: "date" },
      { header: t("updatedAt"), key: "updated_at", type: "date" },
    ],

    mediaChannelsColumns: [
      { header: t("id"), key: "id" },
      { header: t("code"), key: "code" },
      { header: t("name"), key: "name" },
      { header: t("subOf"), key: "sub_media_of" },
      { header: t("createdAt"), key: "created_at", type: "date" },
      { header: t("updatedAt"), key: "updated_at", type: "date" },
    ],
  };
}
