name: Deploy frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (for completeness)
        uses: actions/checkout@v4

      - name: SSH to server and update the frontend container
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -euo pipefail
            cd /home/hussein/deploy
            docker compose pull frontend
            docker compose up -d frontend
            docker image prune -f
