name: Frontend CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (latest + sha)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            haidarsh/frontend-app:latest
            haidarsh/frontend-app:sha-${{ github.sha }}
          cache-from: type=registry,ref=haidarsh/frontend-app:buildcache
          cache-to: type=registry,ref=haidarsh/frontend-app:buildcache,mode=max
